name: Telegram Issue Open Notifications

on:
  issues:
    types:
      - opened

jobs:
  notify-issue:
    environment:
      name: telegram
    uses: jobmetric/github-notify/.github/workflows/telegram-issue-open-notify.yml@master
    with:
      date_format: jalali
      timezone: Asia/Tehran
    secrets:
      bot_token: ${{ secrets.BOT_TOKEN }}
      chat_id: ${{ secrets.CHAT_ID }}

